// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPIU35eD_TLzqyB39fCgDcGgZj5Nrp-oE',
    appId: '1:989103074606:web:0be7fac0d4cc4f175a1ebf',
    messagingSenderId: '989103074606',
    projectId: 'furniture-app-c4df8',
    authDomain: 'furniture-app-c4df8.firebaseapp.com',
    storageBucket: 'furniture-app-c4df8.firebasestorage.app',
    measurementId: 'G-DXPXZFQ5WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB84ZoqtAMObjwppgFS4WzvzR3snX28uHQ',
    appId: '1:989103074606:android:901369b732d107c65a1ebf',
    messagingSenderId: '989103074606',
    projectId: 'furniture-app-c4df8',
    storageBucket: 'furniture-app-c4df8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA42-nO9nINES0tkUTweZ1fIuOL2dfMNoY',
    appId: '1:989103074606:ios:e69f1f2c1d23b0c35a1ebf',
    messagingSenderId: '989103074606',
    projectId: 'furniture-app-c4df8',
    storageBucket: 'furniture-app-c4df8.firebasestorage.app',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA42-nO9nINES0tkUTweZ1fIuOL2dfMNoY',
    appId: '1:989103074606:ios:e69f1f2c1d23b0c35a1ebf',
    messagingSenderId: '989103074606',
    projectId: 'furniture-app-c4df8',
    storageBucket: 'furniture-app-c4df8.firebasestorage.app',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPIU35eD_TLzqyB39fCgDcGgZj5Nrp-oE',
    appId: '1:989103074606:web:0149e926854c6ce95a1ebf',
    messagingSenderId: '989103074606',
    projectId: 'furniture-app-c4df8',
    authDomain: 'furniture-app-c4df8.firebaseapp.com',
    storageBucket: 'furniture-app-c4df8.firebasestorage.app',
    measurementId: 'G-4KLT3K56SD',
  );
}
